---
title: "Example GitHub Pages Document"
author: "Christopher Gandrud"
date: "10 November 2014"
output: 
    html_document:
        fig_width: 6
        fig_height: 4
        fig_align: center
---

This is an simple example of an R Markdown created GitHub Pages page.

## Plots

Here are some examples of plots you can create and include in your page.

## A Map

```{r, warning=FALSE, message=FALSE, results='asis'}
library(googleVis)
library(WDI)

co2 <- WDI(indicator = 'EN.ATM.CO2E.PC', start = 2010, end = 2010)
co2 <- co2[, c('iso2c','EN.ATM.CO2E.PC')]

# Clean
names(co2) <- c('iso2c', 'CO2 Emmissions per Capita')
co2[, 2] <- round(log(co2[, 2]), digits = 2)

co2_map <- gvisGeoMap(co2, locationvar = 'iso2c',
                      numvar = 'CO2 Emmissions per Capita',
                      options = list(
                          colors = '[0xfff7bc, 0xfec44f,
                                    0xd95f0e]'
                          ))

print(co2_map, tag = 'chart')
```

## A time series graph

```{r results='asis'}
library(dygraphs)
lungDeaths <- cbind(mdeaths, fdeaths)
dygraph(lungDeaths) %>% dyRangeSelector()
```

## A network plot

```{r results='asis'}
library(networkD3)
data(MisLinks); data(MisNodes)
forceNetwork(Links = MisLinks, Nodes = MisNodes,
            Source = "source", Target = "target",
            Value = "value", NodeID = "name",
            Group = "group", opacity = 0.8)
```